### ISSUE TITLE
integrate other contacts

### ISSUE THREAD

**Issue by ramack** [WeAreFairphone/android_packages_apps_MyContactsWidget#8]
I suggest to add support for other forms of contacts like Messengers Conversations or Telegram. With an Option ro select whether those  shall be shown or not...

**Comment by Roboe** [comment]
I guess that'd be a real challenge, and I'm not sure if that lines up fine with the [Fairphone Experience](https://medium.com/@impossible_labs/fairphone-designing-a-fair-experience-76725e9514e8).

Introducing those other contacts will impact the algorithm that powers the widget. In fact, that would render it useless. The algorithm uses phone activity (calls and SMS) to calculate most reached contacts. Those other apps you mention don't have (naturally) any mechanism to inform of reached contacts [and this is good for privacy]. Without a well-balanced algorithm the widget is not reliable, unfortunately.

So... I'm out of ideas of how to implement this, really.

**Comment by ramack** [comment]
If not possible it's also fine for me to close this ticket. It was just an idea. Maybe even email could be added... or with a newly invented protocol to connect any communication APP with this one? I don't know, just mentioning ideas from a users point of view.

Perhaps the contacts should be modified 'on access' to store the latest contact date? This might be beyond the scope of this particular app? But who knows - anyone here might have an idea how to solve it...

**Comment by Roboe** [comment]
Woa, don't you think making up another protocol is a huge work only for this widget? It's not viable, really.

Anyway, the thing is that the Contacts app already condenses all ways to communicate with someone and the purpose of the widget is not to replace it. Do you thing that we should open the Contact app's contact card instead of the one that opens right now?
I think that has a lot of sense and I didn't realize until now because I don't really use widgets at all —[KISS Launcher](https://f-droid.org/packages/fr.neamar.kiss/) has contact discovery and history embedded in an omnibox search and history—, so your ideas are really useful, :)

**Comment by ramack** [comment]
Maybe not. I am an android user for maybe 5 months now, so not everything is clear where it should belong to. And from your response it seems, that if the apps have a good contact integration, this feature is implicitly given, which means I should move the ticket to those apps not registering the communication in the contacts, right?

This also answers the questions whether a new protocol makes sense, clearly with NO.

About the contact card I am not sure, right now I like better what is there now, than the Conact app's card, but maybe that is because I don't like the contacts app I am currently using. And both do not have what I would like to have right now. If you want to give the power to the user you can make it configurable, what should happen on tapping...
